[project]
name = "llm-twin"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "loguru>=0.7.3",
    "numpy>=2.3.2",
    "typing-extensions>=4.15.0",
    "zenml>=0.84.3",
]
